spring:
  mail:
#    host: smtp.163.com
#    username: 15123020544@163.com
#    password: Asiainfo@1234
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    username: haoxm@asiainfo.com
    password: Asiainfo@1234567
    host: mail.asiainfo.com
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: ucr_uec
    password: 37!M!a11
    url: jdbc:db2://10.191.115.20:50000/cqect2
